version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm --version
      - npm install
      - ls -lah
  build:
    commands:
      - npm run build
      - ls -lah
  post_build:
    commands:
      - aws s3 sync /dist s3://practive-bucket-deploy-jaedeokdev
      - ls -lah