version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - node --version
      - npm --version
      - npm install
      - ls -lah
  pre_build:
    commands:
      - echo "run test"
  build:
    commands:
      - npm run build
      - pwd
      - ls -lah
  post_build:
    commands:
      - aws s3 sync ./build s3://practive-bucket-deploy-jaedeokdev
      - ls -lah
      - printenv