version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - ls -lah
      - npm install
      - npm run build
      - ls -lah
artifacts:
  files:
    - '/build'
  base-directory: '/'